// Auto-generated Characters object for easy sprite access
// Generated on 2025-07-22T17:03:25.088Z

import type { Goblin01Atlas } from './goblin-01';
import type { Golem01Atlas } from './golem-01';
import type { Golem02Atlas } from './golem-02';
import type { Golem03Atlas } from './golem-03';
import type { Ogre01Atlas } from './ogre-01';
import type { Orc01Atlas } from './orc-01';

// Characters object for easy access with IDE autocomplete
export const Characters = {
  goblin01: {
    name: 'goblin-01' as const,
    atlas: () => import('./goblin-01').then(m => m.goblin01Atlas),
    sizes: {
      '128x128': {
        imagePath: 'goblin-01-128x128-0.png',
        frameCount: 207,
        atlasSize: { w: 1022, h: 1225 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '32x32': {
        imagePath: 'goblin-01-32x32-0.png',
        frameCount: 207,
        atlasSize: { w: 500, h: 286 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '64x64': {
        imagePath: 'goblin-01-64x64-0.png',
        frameCount: 207,
        atlasSize: { w: 1978, h: 197 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
    },
  },
  golem01: {
    name: 'golem-01' as const,
    atlas: () => import('./golem-01').then(m => m.golem01Atlas),
    sizes: {
      '128x128': {
        imagePath: 'golem-01-128x128-0.png',
        frameCount: 207,
        atlasSize: { w: 1022, h: 1281 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '32x32': {
        imagePath: 'golem-01-32x32-0.png',
        frameCount: 207,
        atlasSize: { w: 570, h: 256 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '64x64': {
        imagePath: 'golem-01-64x64-0.png',
        frameCount: 207,
        atlasSize: { w: 1008, h: 395 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
    },
  },
  golem02: {
    name: 'golem-02' as const,
    atlas: () => import('./golem-02').then(m => m.golem02Atlas),
    sizes: {
      '128x128': {
        imagePath: 'golem-02-128x128-0.png',
        frameCount: 207,
        atlasSize: { w: 1023, h: 1308 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '32x32': {
        imagePath: 'golem-02-32x32-0.png',
        frameCount: 207,
        atlasSize: { w: 1000, h: 145 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '64x64': {
        imagePath: 'golem-02-64x64-0.png',
        frameCount: 207,
        atlasSize: { w: 1622, h: 253 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
    },
  },
  golem03: {
    name: 'golem-03' as const,
    atlas: () => import('./golem-03').then(m => m.golem03Atlas),
    sizes: {
      '128x128': {
        imagePath: 'golem-03-128x128-0.png',
        frameCount: 207,
        atlasSize: { w: 1016, h: 1203 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '32x32': {
        imagePath: 'golem-03-32x32-0.png',
        frameCount: 207,
        atlasSize: { w: 115, h: 1218 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '64x64': {
        imagePath: 'golem-03-64x64-0.png',
        frameCount: 207,
        atlasSize: { w: 1014, h: 381 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
    },
  },
  ogre01: {
    name: 'ogre-01' as const,
    atlas: () => import('./ogre-01').then(m => m.ogre01Atlas),
    sizes: {
      '128x128': {
        imagePath: 'ogre-01-128x128-0.png',
        frameCount: 207,
        atlasSize: { w: 2045, h: 614 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '32x32': {
        imagePath: 'ogre-01-32x32-0.png',
        frameCount: 207,
        atlasSize: { w: 511, h: 285 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '64x64': {
        imagePath: 'ogre-01-64x64-0.png',
        frameCount: 207,
        atlasSize: { w: 1018, h: 388 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
    },
  },
  orc01: {
    name: 'orc-01' as const,
    atlas: () => import('./orc-01').then(m => m.orc01Atlas),
    sizes: {
      '128x128': {
        imagePath: 'orc-01-128x128-0.png',
        frameCount: 207,
        atlasSize: { w: 1023, h: 1352 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '32x32': {
        imagePath: 'orc-01-32x32-0.png',
        frameCount: 207,
        atlasSize: { w: 1242, h: 122 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
      '64x64': {
        imagePath: 'orc-01-64x64-0.png',
        frameCount: 207,
        atlasSize: { w: 1679, h: 254 },
        animations: {
          Dying: 'Dying' as const,
          FallingDown: 'FallingDown' as const,
          Hurt: 'Hurt' as const,
          Idle: 'Idle' as const,
          IdleBlinking: 'IdleBlinking' as const,
          JumpLoop: 'JumpLoop' as const,
          JumpStart: 'JumpStart' as const,
          Kicking: 'Kicking' as const,
          RunSlashing: 'RunSlashing' as const,
          RunThrowing: 'RunThrowing' as const,
          Running: 'Running' as const,
          Slashing: 'Slashing' as const,
          SlashinginTheAir: 'SlashinginTheAir' as const,
          Sliding: 'Sliding' as const,
          Throwing: 'Throwing' as const,
          ThrowinginTheAir: 'ThrowinginTheAir' as const,
          Walking: 'Walking' as const,
        },
      },
    },
  },
} as const;

// Type-safe Characters with autocomplete
export type CharactersType = typeof Characters;
export type CharacterKey = keyof typeof Characters;

// Helper function to get character data by name
export function getCharacter<T extends CharacterKey>(name: T): (typeof Characters)[T] {
  return Characters[name];
}

// Get all available character names
export const characterNames = Object.keys(Characters) as CharacterKey[];
